version: "3.8"
services:
  admin:
    image: localhost:3000/${ADMIN_IMAGE}
    stop_grace_period: 10s
    volumes:
      - /data/data:/data
      - /data/log:/log
    ports:
      - "3003:80"
    environment:
      APP_ENV: PRODUCTION
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/health" ]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 60s
        failure_action: rollback
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "2"
          memory: "200M"

  bot:
    image: localhost:3000/${WEB_IMAGE} 
    stop_grace_period: 10s
    volumes:
      - /data/data:/data
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        failure_action: rollback
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "2"
          memory: "500M"
